runtime: nodejs
env: flex
service: default

env_variables:
  NODE_ENV: production
  API_HOST: 0.0.0.0
  API_PORT: 8080
  POSTGRES_HOST: '35.239.36.197'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DATABASE: multiUsers
  DB_HOST: /cloudsql/nodeserverm:us-central1:database-for-nodeserver
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: nodeserverm:us-central1:database-for-nodeserver
  PROJECT_ID: nodeserverm
 # [END env]
network:
 instance_tag: production
 name: default
beta_settings:
  cloud_sql_instances: nodeserverm:us-central1:database-for-nodeserver
